# Generated by Django 4.2.3 on 2024-03-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="bodyimage",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
