# Generated by Django 4.2.3 on 2024-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_message_bodyimage_alter_message_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="bodyimage",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
