# Generated by Django 4.2.3 on 2024-03-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_alter_message_bodyimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="bodyimage",
            field=models.FileField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
