# Generated by Django 4.2.3 on 2024-03-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_room_is_private_room_requested_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='requested_participants',
            new_name='request_to_join',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_private',
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
